project/bmd/migrations/0001_initial.py, project/invitro/migrations/0001_initial.py
Alters the 0001_initial migrations for the Invitro and BMD apps to have respective foreign keys IVExperiment.dose_units and BDM_session.dose_units relate to assessment.DoseUnits instead of animal.DoseUnits. 
This fixes the migration error `django.db.utils.ProgrammingError: relation "animal_doseunits" does not exist` that is encountered when installing HAWC from scratch.
=> alter BMD and Invitro initial migrations

project/utils/api.py
Fixes https://trello.com/c/l5vnR5kF/452-hotfix-null-endpoint-id-cleanup
=> use ternary to set CleanupFieldsFilter ids to ids queryparam or None

project/riskofbias/views.py, project/templates/riskofbias/reviewers_list.html
- replaces IsAuthorMixin with ProjectManagerOrHigerMixin on RoBEditFinal view.
- shows edit icon on ReviewerList if user is author, or if user is PM and rob is final.
=> make RobEditFinal view accessible to all Project Managers

Makefile, docs/Makefile, docs/source/dev_setup.rst, docs/source/index.rst, docs/source/server_setup.rst, requirements/dev.txt
Added new command `make servedocs` which allows the documentation to be rebuilt and automatically regenerated while source-files change. This should make it easier to write documentation and test that formatting is appropriate.
Also added @JoshAddington to the list of HAWC developers.
=> added makefile and command for auto-building documentation

project/assets/mgmt/TaskAssignments/components/FinishedTaskFilter/index.js, project/assets/mgmt/TaskAssignments/constants.js, project/assets/mgmt/TaskAssignments/containers/Assignments/index.js, project/assets/mgmt/TaskAssignments/containers/Root/index.js, project/assets/mgmt/TaskAssignments/index.js, project/assets/mgmt/TaskAssignments/reducers/Tasks.js, project/assets/mgmt/TaskAssignments/reducers/index.js
Adds code-splitting for mgmt/TaskAssignments.
Completes checklist item 4 in https://trello.com/c/OzwVEqzf/521-project-management-next-steps
- For both user-task view, add a checkbox filter at the top to show/hide completed (and abandoned) tasks. By default, hide these tasks.
=> Filter user management tasks

.gitignore, Makefile, bin/dev.sh, docs/source/dev_setup.rst
Add and document an example [tmux](https://tmux.github.io/) developer environment to the HAWC project.  Document how to extend and roll-your-own.
=> add developer tmux scripts

.gitignore, Makefile, bin/dev.sh, docs/source/dev_setup.rst, project/animal/forms.py, project/animal/lookups.py, project/animal/urls.py, project/animal/views.py, project/epi/views.py, project/templates/animal/animalgroup_copy_selector.html, project/templates/animal/experiment_copy_selector.html, project/templates/animal/experiment_detail.html, project/templates/study/study_detail.html, project/utils/views.py
Added copy as new for animal experiment and animal-group models, per trello card: https://trello.com/c/S4jXMPVY/540-copy-as-new-animal-experiment-and-animal-groups.
Also created a view mixin and applied for all standard copy as new models; investigated implementing for data-pivot and search but determined that they have custom implementations that are too different for this generic mixin.
=> Copy as new for animal models

project/epimeta/models.py, project/study/forms.py, project/study/models.py
Closes https://trello.com/c/AZxPhUKD/572-complete-epi-meta-copy-across-assessments
Adds epimeta `copy_across_assessments` ability.
The meta-ness of the data makes the process different from the rest of the studies. The MetaResult has many SingleResults, which link to other studies. The SingleResult.study might not be in the current assessment, so we have to go through SingleResults of all the assessment's Study.MetaProtocol.MetaResults, as well as the SingleResults that link directly to the assessment's Studies.
If the `single_result.study` is being copied over, then it's in the `cw` crosswalk dict and the new id is assigned, otherwise it's not in the crosswalk dict and stays the same. Same with the `single_result.meta_result`.
=> add epimeta copy_across_assessments

.gitignore, docs/source/dev_setup.rst, docs/source/server_setup.rst, project/hawc/celery.py, project/hawc/settings/base.py, project/hawc/wsgi.py, project/manage.py
Closes https://trello.com/c/rMXB0PuT/575-remove-old-required-environment-variables-for-hawc
I cloned this to a new folder and setup a new virtualenv to test out.
Removes old environment variables from hawc/settings/  and docs, and moves notes about adding env vars from dev_setup to server_setup in docs.
=> Remove old required environment variables

project/animal/exports.py, project/animal/models.py, project/animal/views.py, project/summary/forms.py, project/summary/models.py, project/templates/summary/datapivot_form.html
Closes https://trello.com/c/4vcef19D/588-create-new-data-pivot-export-type-to-do-rows-at-the-endpoint-level-as-well-as-the-endpoint-group-level-for-creating-er-diagrams
- Renames EndpointFlat exporters to EndpointGroupFlat, since each row is representative of an EndpointGroup.
- Adds EndpointFlatDataPivot exporter for grouping dose, response, and significance for each EndpointGroup into a single Endpoint row.
- Adds option for `Export Style` to animal bioassay data pivot settings.
=> Animal Endpoint davapivot export

project/assessment/management/commands/assessment_db_dump.py, project/assessment/managers.py, project/assessment/models.py, project/bmd/managers.py, project/bmd/models.py, project/epi/managers.py, project/epi/models.py, project/lit/managers.py, project/lit/models.py, project/myuser/managers.py, project/myuser/models.py, project/riskofbias/models.py, project/study/models.py, project/summary/managers.py, project/summary/models.py, project/utils/models.py
Enables https://trello.com/c/wpoRQefX/612-hawc-data-import-and-export
- `assessment_db_dump` to allow multiple assessment ids for export https://github.com/shapiromatron/hawc/pull/70/commits/d5853a64cead898da1fd32969b82612795dc80d3#diff-b05ec24c7255d4c7f62e435d7c5b41bfR269
- BaseHawcDataExports class https://github.com/shapiromatron/hawc/pull/70/commits/d5853a64cead898da1fd32969b82612795dc80d3#diff-b05ec24c7255d4c7f62e435d7c5b41bfR82 and write_base_data() https://github.com/shapiromatron/hawc/pull/70/commits/d5853a64cead898da1fd32969b82612795dc80d3#diff-b05ec24c7255d4c7f62e435d7c5b41bfR167 for exporting data that would be duplicated across assessments
- multiple model managers
- `include_root` option in AssessmentRootMixin.get_assessment_qs for including the root node in treebeard exports …
=> Refactor assessment_db_dump for multiple assessments

requirements/base.txt
- Django to 1.11.4
- django-selectable to the latest commit: https://github.com/mlavin/django-selectable/commit/66ed38326cbd8ffa611c9648f58343a899cc1e41. I checked the different selectable widgets we're using, and they all work with Django 1.11.4. Based on discussion in https://github.com/mlavin/django-selectable/issues/187, more work is needed before a new release with proper support is finished, so we'll need to check on progress periodically.
=> update django to 1.11, django-selectable to most recent commit

project/epi/models.py
Only caused problems when trying to copy a study across assessments where a GroupNumericalDescriptions record existed.
=> Removed references to child records in childless model

project/utils/svg.py
Closes https://trello.com/c/TLPHRJJf/631-investigate-visualization-download-character-encoding
The urllib parser isn't intended to decode characters not used in a URL, so it can't handle utf-8 encoded characters that aren't basic ASCII characters. Using ISO-8859-1 encoding lets the parser handle more characters.
=> use 'ISO-8859-1' encoding to parse svg for download

project/assessment/views.py
Probably not something y'all would have run into before, but we were getting an error on the About page due to not having some of the data types.
=> Fix for divide by zero error on About page

project/animal/templates/animal/endpoint_detail.html, project/assessment/forms.py, project/assessment/templates/assessment/assessment_detail.html
Implements #97.  
Remove BMD links until BMD online again; added comment to search for in the
future to add back in (3 matches):
`DISABLED UNTIL BMDS SERVER ONLINE (hopefully temporarily)`
=> remove BMD options until BMD is operational again

docs/source/dev_setup.rst, docs/source/server_setup.rst, project/assessment/views.py, project/hawc/settings/base.py, project/hawc/settings/local.example.py, project/templates/hawc/about.html
Create a new application setting, HAWC_FLAVOR, which allows slight changes in behavior based on deployment environment.
Has two possible values: PRIME (default), or EPA. 
Currently, training videos vary slightly depending on which HAWC flavor is being used.
=> HAWC flavors

docs/source/index.rst
Make the link absolute. As written, this is a relative path so if you're reading https://hawc.readthedocs.io/en/latest/ then it tries to load https://hawc.readthedocs.io/en/latest/hawcproject.org which is 404.
=> Fix broken link

client/Makefile, client/hawc_client/__init__.py, client/setup.cfg, docs/source/api.rst, docs/source/development.rst
- added new `Makefile` and commands for pushing hawc to pypi
- updated documentation to reflect installation process
- released first version of hawc-client
=> pip install hawc-client

frontend/assets/nestedTagEditor/actions.js
Bug reported that a user can no longer create tags; this was fixed be replacing the URL and using the correct one.
=> hotfix- fix bug preventing tag creation

hawc/apps/lit/templates/lit/overview.html, hawc/apps/lit/views.py
- Use the `assessment_id` as the pk for the topic model instead of the literature assessment settings
=> change topic-model URL route

frontend/assets/textCleanup/components/Items/BulkForm.js, frontend/assets/textCleanup/components/Items/Header.js, frontend/assets/textCleanup/containers/FieldSelection.js, frontend/assets/textCleanup/containers/Items/App.js, frontend/assets/textCleanup/containers/Items/BulkForm.js, frontend/assets/textCleanup/containers/Root.js
Problem from when we were removing instances of deprecated `componentWillMount`. It was changed to `componentDidMount` within `textCleanup/containers/Root.js`, which made it wait until after render to set `config` in store, when it was expected to be set before the child React components were mounted. Changed it to happen within the constructor so that actions based on this variable are no longer broken.
Also cleaned up PropType errors once it was working.
=> Hotfix: 'clean-extracted-data' hanging

hawc/apps/study/models.py
Fixed permissions to allow project managers the ability to unlock studies, and added helper method to `Attachment` model to make it compatible with `AssessmentPermissionsMixin`:
https://github.com/shapiromatron/hawc/blob/6d3fee1721509093893beda48f58293a0cdda12c/hawc/apps/common/views.py#L101
=> Hotfix: locked study permissions

frontend/animal/Endpoint.js
=> Hotfix: extra quotes on animal group table

hawc/apps/assessment/api.py, hawc/apps/lit/api.py
`AssessmentLevelPermissions` required edit permissions on the reference search API when it should have been read permissions; the subclassed permissions were removed and instead checked locally.
=> Hotfix: reference search permissions

hawc/apps/lit/forms.py, tests/hawc/apps/lit/data/no-id.txt, tests/hawc/apps/lit/data/ris-big-doi.txt, tests/hawc/apps/lit/test_lit_forms.py
Catch a few common RIS errors that are commonly encountered to display useful errors to users for how to fix.
=> catch common RIS errors

frontend/animal/Barplot.js, frontend/animal/DRPlot.js, frontend/assets/shared/utils/helpers.js, frontend/summary/dataPivot/DataPivotVisualization.js, frontend/summary/summary/CrossviewPlot.js, frontend/summary/summary/EndpointAggregationExposureResponsePlot.js, frontend/utils/D3Plot.js, hawc/apps/animal/forms.py
Regression w/ d3 v5 migration, logscale tick behavior changed:
---
---
---
In addition, the following changes were made:
- standardized d3.format for numerical formatting data
- removed unused methods
- fixed bug in crossview plot where range styles were not applied (another d3 v5 issue)
=> logscale axes

frontend/assets/textCleanup/GroupedObjectList.js, frontend/assets/textCleanup/stores.js, hawc/apps/animal/models.py, hawc/apps/animal/serializers.py, hawc/apps/common/api.py
If we're using controlled vocabulary we don't want those fields present when cleaning up endpoints. This PR adds an additional filter to filter items which can be cleaned up to only show those which aren't using a term.
---
---
---
---
=> controlled vocabulary - extraction cleanup exclusion

hawc/apps/vocab/views.py
The combination of a cache and login_required made the page-cache dependent on login rules. This caches the expensive part but still does the login and permissions check.
=> cache expensive part not entire page

hawc/apps/common/models.py, tests/hawc/apps/common/test_common_models.py
A previous change introduced a bug where even if a model had a default ordering, it always default to `id` to prevent non-deterministic query results. This PR introduces a feature to use default ordering where available, and if none is available, default to id.
Prior bug:
https://github.com/shapiromatron/hawc/commit/3ec4783f870cadac282b7e82bdd892ee440f37b5#diff-12d8ff694bfca83829c6d1818f3b0008705913fa5eacb656e41fa9ddc0c5d36cL41
=> hotfix - restore model ordering default when possible

hawc/apps/animal/exports.py, hawc/apps/epi/exports.py, hawc/apps/invitro/exports.py, tests/data/api/api-dp-data-animal-bioassay-endpoint-group.json, tests/data/api/api-dp-data-animal-bioassay-endpoint.json
`distinct` wasn't working since the studies weren't ordered by id, so there was a chance non-unique study ids were being sent to `get_dp_export`
This was causing a problem [here](https://github.com/shapiromatron/hawc/blob/62e253f33c530b012e1507d8ec0b578ec005323f/hawc/apps/riskofbias/models.py#L358), since the json dump would already exist in the mapping, so the default N/A value was being used.
=> Hotfix: N/A scores on data pivot

hawc/templates/includes/navigation.html
Makes the navbar stick to top when scrolling, allows for easier integration tests.
=> Sticky navbar

hawc/apps/animal/forms.py, hawc/apps/assessment/forms.py, hawc/apps/common/forms.py, hawc/apps/common/selectable.py, hawc/apps/epi/forms.py, hawc/apps/epimeta/forms.py, hawc/apps/invitro/forms.py, hawc/apps/myuser/forms.py, hawc/apps/riskofbias/forms.py, hawc/apps/summary/forms.py, hawc/static/js/selectable_bootstrap.js, hawc/templates/base.html
Changed the order of script imports so that conflicting namespaces don't cause django-selectable buttons to not render. Also added custom scripting to render the selectable inputs using bootstrap stylings.
Reference: https://django-selectable.readthedocs.io/en/latest/advanced.html#using-with-twitter-bootstrap
=> Fix django-selectable render problems

hawc/apps/assessment/views.py, hawc/apps/common/views.py, hawc/apps/riskofbias/views.py, hawc/apps/vocab/views.py, tests/hawc/apps/assessment/test_assessment_views.py, tests/hawc/apps/common/test_common_views.py
Make sure the referrer url can be resolved in the hawc namespace, otherwise return the default
=> sanitize referrer

compose/app/sync.sh, hawc/apps/common/management/commands/load_test_db.py, hawc/apps/myuser/admin.py, hawc/main/settings/staging.py
Three updates related to flexibility in deployment environments:
1. Add new diagnostic action in the admin to send a test email to the currently logged in user. This can be used for easily diagnosing email configuration issues.
2. Add new django setting (and django monkeypatch) to set the [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) instead of using the default. This domain name may be required when sending emails via SMTP, and the default value when running in a container is the container ID. This change may be removed in future version of django are updated (see comments in implementation)
3. Update `load_test_db` command to add new argument which only loads the test database if the database is not empty. This can be helpful in some test environments where we wish …
=> Deployment updates

frontend/lit/TagTreeViz.js, frontend/summary/summary/LiteratureTagtree.js, hawc/apps/lit/templates/lit/reference_visual.html, hawc/apps/summary/forms.py, hawc/apps/summary/migrations/0029_tagtree_size.py
Users were reporting issues with tag nodes overlapping. 
Now, when creating a custom tagtree, you can set the figure height and width. This will allow for more space when needed to prevent overlap.
**New inputs:**
**Example collapsed:**
**Example resized:**
=> Make figure height/width configurable for custom literature tagtrees

hawc/services/nih/pubmed.py
Python 3.9 removes `getchildren()`.
https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren
=> Fix Pubmed parser in 3.9

hawc/apps/common/middleware.py, hawc/apps/common/views.py, hawc/main/settings/base.py, requirements/base.txt, requirements/dev.txt, tests/hawc/apps/assessment/test_assessment_views.py, tests/hawc/apps/common/test_common_middleware.py, tests/hawc/apps/common/test_common_views.py
Add new middleware to validate Referer header on safe requests, per updated security scanning requirements. 
CSRF checking in django middleware is only performed for "unsafe" methods per django [documentation](https://docs.djangoproject.com/en/3.1/ref/csrf/#how-it-works) and [IETF](https://tools.ietf.org/html/rfc7231.html#section-4.2.1).   This PR adds Referer middleware checking on safe requests such as a GET. If the Referer doesn't match the server host name, the middleware returns a valid html page that requests a refresh. This will modify the Referer header to the current domain as expected.
This would only be an real issue if a GET request modified server state and used a Referer header to do so, which isn't a real-world condition for this application.
To test real-world conditions, …
=> Middleware - Referer checking on safe http methods

.github/workflows/main.yml, requirements/dev.txt, tests/hawc/apps/epi/test_epi_api.py
We inadvertently had a unit-test which used an external webservice which is periodically down. This update temporarily disables that test, and in the future we'll use [vcr](https://vcrpy.readthedocs.io/en/latest/) to cache the response when it becomes available in the future.
At a future date the commented-test will be uncommented and a cached response will be saved.
=> hotfix - fix tests in CI/CD

hawc/apps/assessment/models.py, hawc/apps/assessment/permissions.py, hawc/apps/assessment/views.py, hawc/apps/common/views.py, hawc/apps/study/models.py, hawc/main/settings/dev.py, hawc/main/settings/local.example.py, tests/hawc/apps/assessment/test_assessment_view_permissions.py, tests/hawc/apps/assessment/test_assessment_views.py
Build a cache for all assessment setting related to view permissions.  Currently, each view is slowed by querying the assessment, plus multiple many to many relations to check if a specific user has permission to view. This PR implements a cache that's refreshed whenever the assessment is saved, which captures all user ids with permission and other assessment settings in a cache. 
Also update development settings to have a single setting to enable or disable cache in dev mode.
The net result of this PR is a speedup for view permission checking and moving db queries to a cache.
=> Assessment permissions cache

hawc/apps/summary/models.py
`json.dumps` injects control characters in the resulting string, so `"href=\"www.example.com\""` becomes `"href=\\"www.example.com\\""`. Our url validator doesn't take this into account, so these control characters should be removed before validation.
=> Fix table url validation

hawc/apps/common/validators.py, hawc/tools/tables/parser.py, tests/data/fixtures/db.yaml
Previously, our html validator erroneously made underlined text invalid. This PR allows makes the `<u>` tag valid.
Text can now be underlined on summary tables:
The underline is rendered correctly in reports:
=> bugfix - add underline to accepted table tags

frontend/riskofbias/constants.js, hawc/apps/assessment/api.py, hawc/apps/assessment/managers.py, hawc/apps/lit/views.py, hawc/apps/riskofbias/api.py
The related field was `domain_assessment`, when it should have been `domain__assessment`
`get_assessment_from_query` returns either the assessment or none if `assessment_id` does not correspond with an assessment. It works in all contexts where this function is called to just have it raise an exception if the assessment does not exist instead.
Another case I found:
This error is thrown when trying to filter by an anonymous user. The fix is to check authentication instead.
__*Note:__ Should we even be rendering this page as an anonymous user? It serves as a launch page for copying searches, which anonymous users wouldn't be able to do to begin with (the `Searches` dropdown doesn't have any options for anonymous users)
=> Miscellaneous error fixes

.github/workflows/main.yml, hawc/apps/animal/signals.py, tests/hawc/apps/animal/test_animal_signals.py
We had a reported data corruption issue where a user edited content in a dosing regime and then after saving, we found multiple endpoint-groups with the same endpoint group id, which shouldn't be possible.
After investigation, we found it was an error in the signal which keeps dose-groups and endpoint-groups synced. If there were multiple representation of dose-groups, for example 5 dose-groups and 2 units, then hawc would create 10 endpoint-groups instead of 5. Further, it would create these even for endpoints where data is not extracted.
Here we fix this issue and write a few tests.
=> dosing regime dose groups hotfix

frontend/bmd/bmds2/components/ModelOptionModal.js, frontend/bmd/bmds2/components/ModelOptionTable.js, requirements/dev.txt
Update frontend to describe dose-dropping functionality since the UI is different than the backend implementation. This is a short-term fix; the correct approach for fixing would be more time consuming and is not worth the effort since we will be moving to bmds 3.4 in the next year and 2.7 will be deprecated.
=> Bmd dose dropped

hawc/apps/assessment/admin.py, hawc/apps/assessment/api.py, hawc/apps/assessment/models.py
If dataset revision does not exist, log the error but return a 404.
Error found in dev/test environments, should not occur in production environment. We still log the error in case it's found.
=> fix 500 error if dataset revision does not exist

hawc/apps/vocab/migrations/0006_require_uid.py, hawc/apps/vocab/models.py
(cherry picked from commit 2cb993abcb89f88b0e0ac15e74e647dc0e55ef87)
This is a separate PR from #417 so that new vocabularies can be loaded before the requirement is added.
=> require UID for vocab.Term EHV

frontend/summary/summaryForms/heatmap/AxisLabelTable.js, frontend/summary/summaryForms/heatmap/DetailTable.js, frontend/summary/summaryForms/heatmap/FilterWidgetTable.js
User-reported bug where a space couldn't be added to a header column because trim() was applied with all changes; this removes the trim() method on all text boxes when editing exploratory heatmap
=> fix bug in exploratory heatmap header text

frontend/summary/summary/ExploreHeatmapPlot.js, frontend/summary/summary/heatmap/HeatmapDatastore.js
Additional, related, changes: 
- set text-align to `end` to right-align heatmap labels on the y-axis
- put polyline borders in a group to better nest svg
- move some svg styles to the group to simplify svg
- update xoffset to move to group instead of individual items
=> right-align y-axis labels in heatmap

hawc/static/css/epa-bootstrap.css, hawc/static/css/epa-hawc.css, hawc/templates/assessment-rooted.html, hawc/templates/crumbless.html, hawc/templates/hawc/home.html, hawc/templates/includes/navigation.html
- when collapsing browser to minimum width, "Contact Us" is now still visible instead of hamburgered
- show sidebar on all pages except home
- dont show top border on first row of the sidebar
=> sidebar updates on non-assessment pages

hawc/main/celery.py
Added expirations to celery beat, so that scheduled tasks don't queue up multiple times if a service is down.
Inspired by [Caktus](https://www.caktusgroup.com/) blogpost: https://www.caktusgroup.com/blog/2021/08/11/using-celery-scheduling-tasks/
=> Add async task expirations for recurring tasks

hawc/apps/summary/templates/summary/visual_selector.html
Reorganized the visual selector page to be more intuitive by mapping to the "steps" in a systematic review.
=> Reorganize visual selector page

hawc/apps/animal/templates/animal/endpoint_detail.html
The Actions dropdown button now only renders when there are items to display.
Logic is confusion: many possible states:
1. if not in detail mode, no action button
1. if user cannot edit and no bmd model, no action button
1. if user cannot edit and bmd model, action button w/ session 
1. if user can edit, show action with endpoint editing, and ....
1. if no bmd and bmd is possible, add create bmd buton
1. if bmd user can edit and bmd, add views session button
1. if bmd not enabled, no bmd model section under actions
=> Fix Actions dropdown button on endpoint detail page

hawc/apps/assessment/tasks.py, hawc/apps/assessment/views.py, hawc/apps/common/forms.py, hawc/apps/common/svg.py, hawc/apps/common/tasks.py, hawc/apps/myuser/signals.py, tests/conftest.py, tests/hawc/apps/assessment/test_assessment_views.py, tests/hawc/apps/common/test_svg.py
Minor updates to improve data validation to handle errors during validation instead of processing.
- Used a django form for the `DownloadPlot` view to handle type checks 
- Added validation check to ensure base64-encoded svg can be properly decoded
- (unrelated) prevent error if unauthenticated user attempts to logout
=> use django form for rasterizer download

hawc/main/settings/staging.py
This permits the use of the sendgrid smtp api for emails within HAWC.
I have tested this using the sendgrid settings provided to me by IARC tech support.
=> add new email provider - sendgrid

hawc/apps/animal/serializers.py, hawc/apps/assessment/actions/media.py, hawc/apps/assessment/admin.py, hawc/apps/common/management/commands/load_test_db.py, hawc/apps/lit/api.py, hawc/apps/lit/models.py, tests/data/fixtures/db.yaml, tests/hawc/apps/animal/test_animal_serializer.py, tests/hawc/apps/lit/test_lit_api.py
- create iris dataset files with `load_test_db` command
- fix media preview admin api w/ json recursion on filesystem paths
- fix lit topic model api when not enough references
- add 30-yr auth token for test fixture
- add name to dose-units search field
- for animal endpoint API creation, relax mutual exclusion in api; not enforced in form view, so this makes the API and form consistent
=> test fixture improvements; api tweaks

frontend/summary/summary/RoBLegend.js
Only show the legend options which are in the metrics selected for a given visualization
Only one score set shown: 
Multiple score sets shown:
=> update rob legend on visuals

compose/app/web.sh, hawc/apps/common/views.py, hawc/main/settings/staging.py
This PR adds a level of redundancy to where audit changes are reported. Previously (see #496); changes to content with resulted in the creation of a new db change record. 
This PR does two things:
1. Adds an application log to `hawc.audit.change` that mirrors the change record in the database
2. Captures all django application logs and serves them through gunicorn in the container environment; these are further piped into the docker logs. (`django > gunicorn > docker`)
=> audit change logs

frontend/summary/dataPivot/ConditionalFormat.js, hawc/apps/assessment/views.py, hawc/apps/lit/templates/lit/ris_export_instructions.html, hawc/apps/myuser/templates/myuser/welcome_email.html, hawc/main/urls.py, hawc/static/css/hawc.css, hawc/templates/admin/base.html, hawc/templates/swagger.html
Add a browsable swagger user interface `{{admin}}/api/swagger/` (staff only):
To fix styling:
- removed custom code styling in css
- switch to [kbd](https://getbootstrap.com/docs/4.5/content/code/#user-input) for a few commands previously using code 
-  conditional formatting options on data pivots
- RIS instructions (`/lit/ris-export-instructions/`)
=> add swagger API user interface 

frontend/lit/NestedTag.js, frontend/lit/ReferenceTreeBrowse/Main.js, frontend/lit/ReferenceTreeBrowse/store.js, frontend/lit/TagTreeViz.js, frontend/lit/components/PaginatedReferenceList.js, frontend/lit/components/TagActions.js, frontend/summary/summary/LiteratureTagtree.js, frontend/summary/summary/Visual.js, hawc/apps/lit/templates/lit/reference_visual.html, tests/data/api/api-visual-tagtree.json, tests/data/fixtures/db.yaml
Create a new `TagActions` component and use for both tagtree visualizations (restoring old functionality that was removed), as well as replacing the existing tag-actions button the the reference tag browsing page
- `/lit/assessment/:id/references/visualization/` (new; restoring old feature removed)
- `/lit/assessment/:id/references/` (replace with new component)
- `/summary/visual/assessment/:id/:slug/` (new; custom visualization tagtrees)
=> tag actions on custom visuals and tables

hawc/apps/myuser/templates/myuser/userprofile_detail.html
Wrap the API token in an ID so automation can easily grab it.
Using javascript:
```javascript
const token = document.getElementById("api_token").innerText
```
Using python:
```python
from lxml import html
html_text = """<div><div id="api_token">asdf123</div></div>"""
dom = html.fromstring(html_text)
print(dom.get_element_by_id('api_token').text)
```
=> wrap token in a html ID

frontend/lit/components/TagActions.js, hawc/apps/lit/api.py, hawc/apps/lit/serializers.py, tests/hawc/apps/lit/test_api.py
Fix a regression where literature report downloads only included current tag, and not child tags. 
This PR changes the default behavior of GET `/lit/api/tags/:id/references/` to include nested tags.
We also add a few options to this API endpoint:
- nested: {t or f} - if t (default), will include descendants
- exporter: {base or table-builder} - which export format to use
With this change, we removed the GET `/lit/api/tags/:id/references-table-builder/` and allow this as a different export format.
=> fix literature reports downloads to include child tags

frontend/shared/textCleanup/GroupedObjectList.js, frontend/shared/textCleanup/stores.js, hawc/apps/common/api/mixins.py, hawc/apps/common/api/viewsets.py, tests/hawc/apps/common/test_api.py
Add an error modal on the data cleanup page if an error occurs:
To test the user interface,  I put a really long string into the study short citation on this page using the text fixture: http://127.0.0.1:8000/assessment/1/clean-extracted-data/#
=> add notification error for 500 error on data cleanup

hawc/apps/lit/forms.py, hawc/apps/lit/managers.py, hawc/apps/lit/models.py, hawc/apps/lit/serializers.py, hawc/services/epa/dsstox.py, tests/hawc/apps/lit/test_api.py, tests/hawc/apps/lit/test_forms.py
Previously, attempting to import a list of HERO ids would create a server error if any duplicates were contained in the list. Now, duplicates are automatically removed from the list when validating the string
=> allow duplicate IDs when importing HERO references

hawc/apps/lit/serializers.py, tests/hawc/apps/lit/test_serializers.py
When uploading a CSV for bulk data tags, duplicate rows are now deleted instead of raising an error
=> allow duplicate rows when bulk data tagging

hawc/templates/500.html
The previous 500 error page displayed improperly when a error occurs because no context is passed, causing layout errors:
> The default 500 view passes no variables to the 500.html template and is rendered with an empty Context to lessen the chance of additional errors.
https://docs.djangoproject.com/en/3.2/ref/views/#the-500-server-error-view
500 error page no longer inherits the base.html template. Now it is a simple page with the Error message and links to Home, About, and Contact Us
Note that this view doesn't attempt to apply any specific "HAWC flavor" or skin on the page, since they require context variables. An alternative approach may have been to override the 500 response handler to pass in those settings, but since this page isn't not hopefully ever viewed, but it goes against …
=> Update 500 error page

hawc/apps/assessment/templates/assessment/assessment_detail.html, hawc/apps/myuser/lookups.py, hawc/apps/myuser/management/commands/scrub_db.py, hawc/apps/myuser/managers.py
- Update assessment detail view so inactive users are no longer displayed
- Update assessment update view so that inactive users which have been selected now say `<inactive user>` instead of `None`; they are still not available via autocomplete
- Update the `scrub_db` mgmt command to anonymize the external id and generate a sensible default
=> fix display of inactive users; anonymize external_id

hawc/apps/summary/models.py
Fixed an error that was being thrown on the Visual create page. This was a regression from #543.
This should be the last regression that needs to be addressed; the following regex captures `Model.CONSTANT` and was used to search the code base for any other infractions, and none were found.
```
(?<!constants\.)(?<!\w)(Permission|Group|ContentType|Session|Site|LogEntry|Token|TokenProxy|Revision|Version|Tag|TaggedItem|HAWCUser|UserProfile|DSSTox|Assessment|Attachment|DoseUnits|Species|Strain|EffectTag|BaseEndpoint|TimeSpentEditing|Dataset|DatasetRevision|Job|Communication|Log|Blog|Content|Term|Entity|EntityTermRelation|LiteratureAssessment|Search|PubMedQuery|Identifiers|ReferenceFilterTag|ReferenceTags|Reference|RiskOfBiasDomain|RiskOfBiasMetric|RiskOfBias|RiskOfBiasScore|RiskOfBiasScoreOverr …
```
=> Fix: Error on Visual create page

hawc/services/utils/ris.py, tests/hawc/services/utils/data/accession-numbers.txt, tests/hawc/services/utils/test_ris.py
Improve accession number parsing. Values equal to a string of "null" converted to None. Also added tests.
Users reported cases where multiple references were imported and unintentionally merged together. This was determined that the RIS file had a null value `AN  - null`. Since accession numbers are treated as strings, the null value was determined to be an identical number, and therefore references were merged together.
=> improve accession number parsing in RIS

hawc/apps/riskofbias/serializers.py, tests/hawc/apps/riskofbias/test_api.py
Adds a validation check to the rob metric serializer; now all metric scores should have a metric_id that is in the required metrics list for the study
=> metric validation in riskofbias api creation

frontend/summary/summaryTable/evidenceProfileTable/IntegrationForm.js, frontend/summary/summaryTable/evidenceProfileTable/Table.js, hawc/apps/assessment/migrations/0030_assessment_part1.py, hawc/apps/summary/migrations/0036_ept_summary_judgment_other.py, hawc/tools/tables/ept.py
Added "Other inferences" to the summary judgment cell in HAWC's EPTs.
|Without text|With text|
|-----|-----|
|![image](https://user-images.githubusercontent.com/46504563/158903669-07925397-22ab-4d2f-8139-861ad6fa7292.png)|![image](https://user-images.githubusercontent.com/46504563/158903792-c600d385-70ca-4729-b9d2-e36e8d5e2464.png)|
=> Add "Other inferences" field to summary judgement cell in EPT

docs/source/development.rst, make.bat
Adds startdb command to make.bat, which starts the postgres database for working in a dev environment.
=> Add command to start postgres on windows

hawc/apps/myuser/management/commands/scrub_db.py, hawc/main/settings/base.py, scripts/client/bioassay-crud.ipynb, scripts/client/lit-crud-references.ipynb, scripts/client/lit-tagging-references.ipynb, scripts/client/r-client.ipynb, tests/frontend/integration/tests/login.py
Update the scrubbed database admin name and password to match the test fixture database. Less context switching between using "real" data and "test" data.
The admin email/username is `admin@hawcproject.org`, and the password is now `pw`.
=> update scrub_db admin names

frontend/riskofbias/robStudyForm/Root.js, frontend/riskofbias/robStudyForm/store.js
Added a "Save and continue editing" button to the RoB form, which will save the data without redirecting the user to a different page.
Also added a "toast" (2s) to notify user when changes were saved.
=> "Save and continue editing" button on risk of bias form

frontend/lit/components/Reference.js, frontend/riskofbias/robStudyForm/Completeness.js, frontend/riskofbias/robStudyForm/store.js, frontend/shared/utils/helpers.js, hawc/apps/riskofbias/constants.py, hawc/apps/riskofbias/migrations/0026_fix_blank_text.py, hawc/apps/riskofbias/models.py, tests/data/api/api-summary-table-set-data.json, tests/data/fixtures/db.yaml
The client and server tests for determining if a study evaluation is complete were not returning the same answer; this PR corrects this.  A study evaluation is now marked complete if the following are true:
- All non-NR scores are marked as complete
- All NR scores with non-blank text are marked as complete
The default score when a new evaluation is created is NR with blank text. These two rules ensure that each score has been "touched" in one way or another
=> fix blank text in study evaluations

hawc/apps/assessment/models.py, hawc/apps/common/helper.py, hawc/apps/common/renderers.py, hawc/apps/lit/api.py, hawc/apps/lit/forms.py, hawc/apps/summary/forms.py, hawc/apps/summary/migrations/0017_datapivotupload_excel_file.py, hawc/apps/summary/models.py, hawc/templates/includes/epa/footer.html, requirements/base.txt, tests/hawc/apps/common/test_helper.py, tests/hawc/apps/common/test_renderers.py
Updated excel exporter to check if an IllegalCharacterException is thrown, and if so, clean string data in the data frame so it should be able to be exported.
Also updated to the latest version of related packages, since they didn't appear to cause any issues:
- [pandas](https://pandas.pydata.org/docs/whatsnew/index.html): 1.4.1 -> 1.4.3
- [openpyxl](https://openpyxl.readthedocs.io/en/stable/changes.html): 3.0.9 -> 3.0.10
Also removed our custom `read_excel` method since it did what is now the [pandas default](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html) of using openpyxl
Fixes #644
=> catch Excel export IllegalCharacterException

frontend/summary/summary/ExploreHeatmap.js, frontend/summary/summary/heatmap/HeatmapDatastore.js, frontend/summary/summaryForms/heatmap/VisualCustomizationPanel.js
The computed `matrixDataset` is the first hurdle when it comes to rendering large heatmaps: the fix here is to split the `HeatmapDatastore` constructor so that a few properties set in the constructor are used to determine if the heatmap is too large, while the `initialize` method continues the computation intensive initialization.
Note:
- It still hangs a little to perform the basic calculations to determine table size when the table is REALLY large, but it should not freeze the page.
=> Prevent exploratory heatmaps that are too large from rendering

hawc/apps/hawc_admin/api.py, hawc/apps/hawc_admin/urls.py, tests/hawc/apps/hawc_admin/test_api.py
Added a viewset for admin diagnostics purposes: the first being a throttle endpoint.
`/admin/api/diagnostic/throttle/`
You must be an admin in hawc to be able to access this read-only API.
=> Admin diagnostics API

frontend/shared/utils/rasterize.js
Fixes a bug where downloading a visual as a PNG or SVG on the live site would instead redirect to a new page.
Related fix: https://stackoverflow.com/questions/62828321/
It looks like it's related to the google tag manager, which is only enabled in produciton.
=> fix image download redirect bug

hawc/apps/animal/models.py
When validation fails on endpoint create, the previous vocabulary terms put into the form were lost. This is because it was relying on values from `form.initial` instead of `form.data`!
This fix uses the `BoundField` value instead of values from `form.initial` when rendering the form; this will get the correct value since it takes into account whether the form is bound or not.
=> Correctly populate vocabulary terms on animal endpoint form

hawc/static/patched/dal/3.9.4/js/autocomplete_light.js
Adds a global counter that increments when a select2 component is initialized. This is used in combination with the input element's id and a randomly generated number to create a more robust unique id for each select2 component.
=> Make unique id for select2 components more robust

frontend/shared/components/VisualToolbar.js, frontend/shared/utils/D3Plot.js, frontend/shared/utils/rasterize.js
Add JPEG export format for downloading large visuals where compression is needed:
Fixed two additional issues:
1. Fixed cases where the rasterized image was scaling incorrectly (use `getBoundingClientRect`)
2. Fixed cases where extremely large canvas (>32k pixel height/width) cannot be exported because of [browser limits](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#maximum_canvas_size)
=> SVG rasterization fixes

hawc/apps/animal/exports.py
Fixed a rare edge case where the number of dose-groups for a given tabular set may be greater than the total number of dose groups for a visual, for endpoints with many dose groups but no data are extracted. This change made the code more confusing, so a comment was added to describe why it's required.
=> hotfix - dose-group count in data pivot

frontend/summary/summaryTable/evidenceProfileTable/EvidenceForm.js, frontend/summary/summaryTable/evidenceProfileTable/Table.js, hawc/tools/tables/ept.py, tests/data/fixtures/db.yaml
Swapped the positions of increased/decreased certainty factors in evidence profile tables.
---
**EPT form**
---
**EPT web report**
---
**EPT word report**
=> Swapped EPT position of increase/decrease factors

frontend/lit/Reference.js, frontend/lit/TagReferences/Main.js, frontend/lit/TagReferences/store.js, hawc/apps/lit/models.py, hawc/apps/lit/templates/lit/_reference_tag_conflict.html, hawc/apps/lit/views.py, hawc/static/css/hawc.css
This is an example of how we can handle deleting resolved tags when conflict resolution is enabled.
When user tags don't exist for a reference, the resolved tags are added by default:
> ![image](https://user-images.githubusercontent.com/46504563/204598400-89bf4c17-7232-461c-87c4-e79beb130500.png)
From here, a user can add additional tags and also remove resolved tags:
> ![image](https://user-images.githubusercontent.com/46504563/204598581-ebe9f4b9-6a82-4826-8825-156afbe6282a.png)
If a resolved tag is removed, it is still displayed with a strikethrough. Clicking on it again will reapply it.
=> Enable deletion of resolved reference tags

frontend/lit/TagReferences/Main.js, frontend/lit/TagReferences/store.js, hawc/apps/lit/api.py, hawc/apps/lit/managers.py, hawc/apps/lit/models.py, hawc/apps/lit/templates/lit/reference_tag.html, hawc/apps/lit/views.py, hawc/static/css/hawc.css
Limited the tagging view to only show 100 references at a time
>![image](https://user-images.githubusercontent.com/46504563/206247091-a5882f5f-9f77-42e6-8731-b4a5823dcb5b.png)
The save alert has been updated and moved from beside the "Save and next" button to right below that header. It fades in and then out whenever tags are saved.
A custom save alert pops up if tags where automatically resolved when saved. For example:
The only unresolved user tag here is from Project Manager (Exclusion -> Tier I)
>![image](https://user-images.githubusercontent.com/46504563/206244462-371cf6ab-c423-4a26-ad19-86bd8beb7579.png)
If another user goes to the tagging view, applies the same tags as the other unresolved user tags, and clicks "Save and next"... …
=> Paginated tagging and updated save alerts

hawc/apps/lit/api.py, hawc/apps/lit/models.py, hawc/apps/lit/templates/lit/_conflict_resolved.html, hawc/apps/lit/templates/lit/_reference_tag_conflict.html, hawc/apps/lit/templates/lit/conflict_resolution.html, hawc/apps/lit/views.py, hawc/static/css/hawc.css, tests/data/fixtures/db.yaml
* On conflicts resolution page, filter to only show cases where the count of is_applied=False is > 1
* Paginate conflict resolution page, 100 at a time
* Add Actions button to references in the conflict page, with options to:
* Tag any reference if you want to edit/create your own tags on that reference
* Edit reference details
* view reference tag history
* Add an Assesssment.Log for whenever conflicts are resolved, log the ref id, and tag id set which includes all includes and excludes
=> Improvements to the Conflict Resolution View

hawc/apps/epi/forms.py
Users reported difficulty in data entry for `epi.Result` groups for cases where there are multiple groups named the same thing across comparison sets. Therefore, we add the comparison set name in addition to the group name for the data entry label.
| Old | New |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/999952/206282013-8cc107d2-2d9c-4c95-8ec5-2450234ab17a.png)  | ![image](https://user-images.githubusercontent.com/999952/206282036-41a0bd6c-2235-4fdd-a3f4-da2d767ba816.png)  |
=> show comparison set name for group on the result form

hawc/apps/lit/api.py, hawc/apps/lit/managers.py, tests/conftest.py, tests/hawc/apps/lit/test_api.py, tests/integration/test_lit.py
* adds tests for api both `/lit/api/reference/:id/tag/` and `/lit/api/reference/:id/resolve-conflicts/`
* checks permissions
* checks functionality
* tests assessments with conflict resolution enabled and disabled
* adds integration tests for new conflict resolution view
* checks that the new pages load
* checks that text highlights, etc.
=> Add Conflict Resolution Tests

frontend/summary/summary/TableauDashboard.js, tests/integration/test_summary.py
Updates TableauDashboard component to use the current API v3 instead of the API v1.
This is a cherry pick of #757 to merge on the main branch instead of next; work originally done by @munnsmunns
=> Update to tableau API v3

hawc/main/settings/base.py
Make cookie domain/name configurable via environment variables. Use the django defaults by default
- [Session Cookie Domain](https://docs.djangoproject.com/en/4.1/ref/settings/#session-cookie-domain) - defaults to None; a standard domain cookie (django default)
- [Session Cookie Name](https://docs.djangoproject.com/en/4.1/ref/settings/#session-cookie-name) - defaults to `sessionid` (django default)
=> Configurable session cookies

hawc/apps/animal/filterset.py
After filterset rewrite, when filtering on a dose-units on `/ani/assessment/:id/endpoints/`, duplicate endpoints were created for each dose-units. This PR removes the duplicate rows for the same endpoint.
=> hotfix-  duplicate rows when filtering by dose-units

frontend/summary/summary/ExternalSiteVisual.js, frontend/summary/summary/TableauDashboard.js, hawc/apps/common/validators.py, hawc/apps/summary/constants.py, hawc/apps/summary/forms.py, hawc/apps/summary/migrations/0040_tableau_filters.py, requirements/dev.txt, tests/data/api/api-visual-embedded-tableau.json, tests/data/fixtures/db.yaml, tests/hawc/apps/common/test_validators.py, tests/hawc/apps/summary/test_forms.py
Add the ability to filter Tableau data via the API. The screenshots below just copy and pasted the help-text examples. Examples were taken from the latest Tableau embedding documentation: https://help.tableau.com/current/api/embedding_api/en-us/docs/embedding_api_filter.html#filtering-example
Only shows two states:
---
Also updated `wheel`, which had a [CVE](https://nvd.nist.gov/vuln/detail/CVE-2022-40898), though it's not installed in production so we don't anticipate this to be an issue in production.
=> add Tableau filters to embedded Visuals

hawc/apps/riskofbias/serializers.py, hawc/apps/riskofbias/templates/riskofbias/rob_edit.html, hawc/apps/study/models.py, hawc/apps/study/templates/study/study_detail.html
- added alert to www.haw.epa.gov/study/x/ page if no data metric is chosen
=> Better message when there is no study type

hawc/apps/lit/forms.py
A user shouldn't be able to change the source (HERO, PubMed) after an import has been executed. Also update the help text to explain why the fields are missing.
=> remove source change for literature import update

hawc/apps/animal/views.py
Fix 500 error when an invalid `dose_units` is passed, for example: `/ani/assessment/:id/endpoints/?dose_units=foo`
=> fix 500 error with invalid dose units

.github/workflows/main.yml, Makefile
Run coverage in CI/CD and add a report summary to the job action. 
For example:
https://github.com/shapiromatron/hawc/actions/runs/5612666910?pr=859
The detailed html coverage report is also available as a downloadable artifact
=> add coverage report to github action

hawc/apps/assessment/templates/assessment/fragments/assessment_list_public.html, hawc/apps/assessment/templates/assessment/fragments/assessment_list_team.html, hawc/apps/epiv2/api.py, hawc/apps/summary/templates/summary/visual_list.html, hawc/main/urls.py
- Add the `eco` and `epiv2` apps to the openapi specification available on the admin
In addition, a minor change to templates:
- strip tags before truncating text
=> Add epiv2 and eco to openapi specification

client/hawc_client/assessment.py, hawc/apps/assessment/api/viewsets.py, hawc/apps/assessment/serializers.py, hawc/apps/assessment/urls.py, tests/hawc/apps/assessment/test_api.py
Add an admin only API endpoint for creating, updating, and deleting assessments.
=> Add API for creating Assessments

hawc/apps/summary/templates/summary/datapivot_form.html
There was a bug in the Django template for the data pivot file upload form that was breaking the javascript that added auto-slugification and quillified the caption field. This PR fixes it by adding a default value when declaring the javascript variables instead of having the template leave the declared value blank.
=> Fix data pivot file upload form javascript

frontend/animal/Experiment.js, hawc/apps/animal/migrations/0023_update_help_text.py, hawc/apps/animal/models.py
Changed "comments" key in column name:
Updated "help text":
=> Update experiment label

frontend/animal/EditEndpoint.js, frontend/animal/Endpoint.js, frontend/animal/EndpointCriticalDose.js
Fix a bug where users couldn't set or view NOEL/LOEL for endpoints where data was not extracted.  
This bug would only occur if a user created an endpoint, but didn't extract any dose group data. Then, when they tried to update the endpoint, it didn't have dose units available so the LOEL select input didn't have any options.
It also failed on the read-only view of view.
=> Fix NOEL/LOEL form and display

hawc/apps/epiv2/api.py
Enable filtering by study identifier on the epiv2 design API.
Example:
- `/epidemiology/api/design/?assessment_id=123`
- `/epidemiology/api/design/?assessment_id=123&study=123456`
This was extracted from #888 in preparation for the quarterly release.
=> epi design api - allow filtering by study id

hawc/apps/assessment/filterset.py, hawc/apps/assessment/managers.py, hawc/apps/assessment/views.py
Fix bug where `/assessment/all/` duplicated assessments based on the number of people assigned to various roles. The previous implementation made duplicative assessments since it was generating a row for each assessment-user combination; to dedup using the distinct() disabled our ability to have a custom sort ordering. 
The new approach breaks adds an `Exists` annotation to the assessment so we prevent the duplicates; query performance is actually faster despite the extra annotations.
=> fix assessment list to make distinct by assessment

hawc/apps/animal/managers.py, hawc/apps/animal/models.py, hawc/apps/assessment/models.py, hawc/apps/bmd/models.py, hawc/apps/eco/models.py, hawc/apps/epi/models.py, hawc/apps/epimeta/models.py, hawc/apps/epiv2/models.py, hawc/apps/hawc_admin/methods/daily_changes.py, hawc/apps/invitro/models.py, hawc/apps/lit/models.py, hawc/apps/mgmt/models.py, hawc/apps/riskofbias/models.py, hawc/apps/study/models.py, hawc/apps/summary/models.py, hawc/apps/vocab/models.py, hawc/main/settings/base.py, requirements/base.txt
Migrates HAWC to Django version 5.0.0
The only thing I could find that broke was wagtail, which required a small update to the next version
I wasn't able to find anything in our codebase that is on the list of [backwards incompatible changes](https://docs.djangoproject.com/en/5.0/releases/5.0/#backwards-incompatible-5-0).
=> migrate to Django 5.0.0

hawc/apps/mgmt/templates/mgmt/fragments/rob_reviews.html, hawc/apps/mgmt/templates/mgmt/user_assessment_task_list.html, hawc/apps/mgmt/templates/mgmt/user_task_list.html, hawc/apps/mgmt/views.py, hawc/static/css/epa-bootstrap.css, hawc/static/css/hawc.css, hawc/templates/includes/_navigation_links.html
A prior PR, #808, removed what we thought was an unused list of study evaluations a user is currently assigned but have not yet completed. We heard from users that this feature was used, so we've added it back in this PR.
- Add a list of incomplete study evaluations at the assessment mgmt level, as well as the overall user level
- `/mgmt/assessment/:id/tasks/`
- `/mgmt/tasks/`
--- 
In addition, updated the navbar to only show the "about" and "resources" pages if the user is not logged in and the new documentation tab is not enabled. I found that even with a "wide" laptop monitor of 1440px, with the EPA flavor of the styles, it wouldn't fit on the a single line with the HAWC title as well.
=> Risk Of Bias review tasks dashboard

frontend/lit/ReferenceTreeBrowse/Main.js, frontend/lit/ReferenceTreeBrowse/ReferenceTableMain.js, frontend/lit/ReferenceTreeBrowse/store.js, frontend/lit/TagTreeViz.js, frontend/lit/components/ReferenceTable.js, frontend/shared/components/Paginator.js, hawc/apps/common/api/pagination.py
The references list view used to render all references for a given tag. However, if there were hundreds or thousands of references for a given tag, it became slow to load and hard to navigate for a user.
This pull request adds pagination to this view. Counts in the tag tree and histogram remain the same, however only 25 references are loaded at a time, and the select box on the left only contains the references on the page.
A more intrusive solution that could speed it up further would be to make an API call that returns a paginated response. However, both the tag tree and year histogram rely on the full list, and the tag tree and histogram are used in other places besides this view so it would be a much bigger change. A future PR could involve making API endpoints that retrieve counts …
=> Add pagination to the references list view

hawc/apps/myuser/admin.py, hawc/apps/udf/admin.py, hawc/apps/vocab/admin.py
Prevent deletion of three models in the admin, which instead have an active flag in the case of users, or deprecation flag in case of UDF Forms and Terms.
Also, updated the admins for UDF forms to inherit form the correct class, along with some basic information on the list view form.
=> disable deletion of some models in admin

hawc/apps/animal/forms.py, tests/hawc/apps/animal/test_views.py
Fix change in how Django 5 handles choice fields so that the choices are sliced directly instead of the form model field choices, which no longer seems to work. I did a quick keyword search in the codebase and didn't see any other cases where this may have been an issue.
Also wrote a test to test the behavior on the views, and raised code coverage for the forms and views:
=> hotfix - fix generational animal group form

hawc/apps/epi/exports.py
There are two issues in the epi exports that are addressed in this PR:
- If an empty queryset is used in one of the exporters it would break when attempting to access properties on the first object in the queryset (ie None).
- If `groupby` results in no groups then `apply` calls would just return an empty dataframe with all the original columns; this behavior was interfering with later `join` calls in one of the exporters.
=> Fix epi orm exports

hawc/apps/common/dynamic_forms/__init__.py, hawc/apps/summary/forms.py, hawc/apps/summary/templates/summary/visual_detail_image.html, tests/data/fixtures/db.yaml, tests/hawc/apps/summary/test_forms.py
Add image options to summary visuals, after noticing some high resolution pixels scale and look way too big for a screen.
Added two new options when configuring a summary image:
* alt-text (required): text required to display on image for accessibility purposes
* max_width (optional; default 1000px) - if specified, the maximum width of an image. If unspecified, it will grow to 100% of the image width in pixels. The image now auto-shrinks on mobile views too.
Example; max width of 600px:
And a mobile view of 400px wide:
=> Add summary.Visual image options

hawc/apps/assessment/forms.py, hawc/apps/assessment/views.py, tests/hawc/apps/assessment/test_views.py
We were getting some spam on our contact us page, so we disabled anonymous contact us (#145) in 2019.  Instead of disabling, we revised the contact page to use use [turnstile](https://developers.cloudflare.com), so anonymous human users can still contact. This uses the same patterns in #775 and #1004.
If turnstile is not enabled, contact-us is disabled for anonymous users.
=> allow anonymous contact us w/ turnstile enabled

frontend/summary/dataPivot/DataPivotVisualization.js, hawc/apps/assessment/constants.py, hawc/apps/lit/views.py, hawc/apps/study/forms.py, hawc/apps/summary/forms.py, tests/hawc/apps/study/test_views.py, tests/hawc/apps/summary/test_forms.py
Fix assorted errors encountered by users with our 2024.Q1 release. 
1. Fix regression in data pivot visualizations, where OR filters accidentally filtered all content out except one row (we had a Map, but the key for all items was undefined so there was only one item in the map); regression in #991 
2. Fix an N+1 query error on the reference search page; regression in #913
3. Fix an error when converting a literature reference to a study, introduced by the UDF form integration; regression in #906 
4. Add an additional check for data pivot file uploads to check the extension
=> bugfixes from 2024.Q1 release

docs/docs/development.md, hawc/apps/assessment/constants.py, hawc/apps/assessment/models.py, hawc/apps/assessment/permissions.py, hawc/apps/assessment/templates/assessment/assessment_detail.html, hawc/apps/assessment/views.py, hawc/apps/bmd/views.py, hawc/apps/common/views.py, hawc/apps/invitro/views.py, hawc/apps/lit/views.py, hawc/apps/riskofbias/views.py, hawc/apps/summary/views.py, tests/integration/test_invitro.py
Add new permission class options for views.  Previously, the project manager and team member classes always checked not only that the user is a project manager or team-member, respectively, but also that the content they're trying to view is editable. This is ideal for views that edit content, but is not ideal for read-only views where even if the content is not editable, the team should be able to view.
This work adds two new options, `TEAM_MEMBER_EDITABLE`, and `PROJECT_MANAGER_EDITABLE`.  These options work just as `TEAM_MEMBER` and `PROJECT_MANAGER` did before. The existing classes were updated to only check for role, and not for edibility status for object.
```py
class AssessmentViewPermissions(models.IntegerChoices):
PROJECT_MANAGER = 1
TEAM_MEMBER = 2
VIEWER = 3 …
```
=> new permission classes

.github/workflows/main.yml
There were a number of github action warnings for using deprecated actions; these were updated to the latest versions. In doing so, we were able to use built-in python and javascript caching using their respective setup actions, instead of manually implementing package caching in our actions.
* Old action w/ warnings: https://github.com/shapiromatron/hawc/actions/runs/8850211441
* New action w/o warnings: https://github.com/shapiromatron/hawc/actions/runs/8990924996
```
frontendNode.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, actions/cache@v3, actions/upload-artifact@v3. 
frontendThe `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more …
```
=> update github action

hawc/apps/vocab/api.py
Unauthenticated users previously got a 405 error when trying to download the EHV data. This fixes that bug!
=> make EHV download public

hawc/apps/common/models.py, tests/hawc/apps/common/test_models.py
Write a simple utility function that given a SQL query statement, return a iterator of dictionary results. This can be helpful for development when experimenting w/ SQL directly instead of the ORM.
=> add a simple SQL select query

compose/app/Dockerfile
Some deployments now require a [FIPS](https://www.nist.gov/standardsgov/compliance-faqs-federal-information-processing-standards-fips) compliant operating system in the docker container. It doesn't appear that debian actively tests or supports compliance ([here](https://lists.debian.org/debian-doc/2022/09/msg00004.html)), so we switched to [CentOS Stream](https://www.centos.org/centos-stream/), the upstream of RHEL. 
A few useful links:
* [Container Registry](https://quay.io/repository/centos/centos)
* [Packages](https://centos.pkgs.org/)
=> switch from python:3.12-slim-bullseye to centos:stream9-minimal

hawc/apps/animal/api.py, hawc/apps/epiv2/api.py, tests/hawc/apps/animal/test_api.py, tests/hawc/apps/epiv2/test_api.py
Add a filter for the animal and epiv2 full exports to limit results to specific study ids using the `study_ids` param.
=> Study filter for exports

hawc/apps/common/autocomplete/registry.py, tests/hawc/apps/common/test_autocomplete.py
Prevents autocomplete from causing 500 errors when users send a bad request.
=> Catch FieldErrors and ValidationErrors in autocomplete

hawc/apps/assessment/models.py, hawc/apps/assessment/templates/assessment/assessment_detail.html, hawc/apps/riskofbias/actions/rob_clone.py, hawc/apps/riskofbias/serializers.py, hawc/apps/riskofbias/views.py, hawc/apps/study/models.py
Minor updates to permissions.
- Remove user_can_edit_assessment in favor of user_is_project_manager_or_higher
- Put team-member information in a blue box on assessment page so it is more easily identifed
- Add assessment id to detail page
=> remove user_can_edit_assessment

frontend/summary/summaryTable/studyEvaluationTable/store.js
This fix adds a trailing forward-slash to the short citation links that SET tables create by default for that column, so that if a user ever customized them they won't fail validation due to a missing trailing slash.
=> Fix for conflict between SET url setting and url validation

.github/workflows/main.yml, pyproject.toml
Add a minimum coverage of 91.5%. This will fail in CI/CD if we go below this number. It's expected we'll revisit this number and hopefully increase it quarterly.
> If you provide a --fail-under value, the total percentage covered will be compared to that value. If it is less, the command will exit with a status code of 2, indicating that the total coverage was less than your target. This can be used as part of a pass/fail condition, for example in a continuous integration server. This option isn’t available for annotate.
https://coverage.readthedocs.io/en/latest/cmd.html#html-reporting-coverage-html
=> add minimum python coverage number

hawc/apps/assessment/forms.py, hawc/apps/assessment/models.py
Swagger display failed b/c the choices were a callable which converted to executable yaml, which fails in our swagger display. Fix so it's no longer a callable, which fixes the openapi rendering on `/admin/api/swagger/`
=> fix display choices for swagger display /admin/api/swagger/

frontend/summary/dataPivot/DataPivotVisualization.js
Fixed a possible regression in #993.
On data pivots, for all conditional formatting when using the "discrete-style" type of conditional formatting, always cast to a string for both the conditional formatting rule, and the value for the observation in question.
Previously, we used to cast the observation, but not the rule, which could break in some cases.  This should be much more robust, and a string comparison should always be valid for "discrete-style" conditional formatting. The other styles such as "point-size" and "point-color" need to be numeric for scaling and shading gradients, but these discrete rules can use string matches.
As an example, this will fix the control formatting for `/summary/data-pivot/assessment/100500243/DCS-IHD-case-controlcohort-ratios-water-categ-9182/`.
=> data pivot - fix conditional formatting on numeric data

.github/workflows/main.yml, .github/workflows/publish.yml, make.bat
Automatically publish [hawc-client](https://pypi.org/project/hawc-client/) to pypi when a branch is tagged with a `hawc-client` tag.
In addition to changes in this PR:
* Create a new github environment named `publish`, and restrict to the `main` branch
* Add a secret to the `PUBLISH_PYPI` environment variable
As an example, see [this action](https://github.com/shapiromatron/hawc/actions/runs/11485959210/job/31971386217) which resulted in a complete push to test pypi; the final PR made some [changes](https://github.com/shapiromatron/hawc/pull/1124/commits/b57a8d66e9e638015bc1ed120a36b27760685f69) to limit when this can be executed, and only push from the main branch. 
---
Reference:
* https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
* …
=> github publish hawc client

client/pyproject.toml, hawc/apps/animal/templates/animal/animalgroup_detail.html
Move the UDF table on the animal group detail page to above the endpoint list
=> Move UDF table on animal group detail page

client/hawc_client/assessment.py, hawc/apps/assessment/api/viewsets.py, tests/client/test_client.py, tests/hawc/apps/assessment/test_api.py
Adds an API endpoint at `assessment/api/assessment/team_member/` that returns all Assessments where the user is a team member or project manager.
=> Add team_member API endpoint

hawc/apps/common/templates/common/crispy_layout_filter_field.html, hawc/static/css/hawc.css
- Add animation to caret dropdown button
- Add screen-reader friendly labels/help text to fields
- Replace  help text in 'title' with error message for appended fields
=> Improve inline filter field

.github/workflows/main.yml, pyproject.toml
If CI fails because our coverage number decreases, it was not previously clear to the developer as to why the pipeline failed.  This PR should better display to the user why a failure occurred.
Now, we see a clear message with the failure:
```
========== 769 passed, 24 skipped, 728 warnings in 143.88s (0:02:23) ===========
Wrote HTML report to coverage/index.html
Coverage failure: total of 91.9 is less than fail-under=99.9
Error: Process completed with exit code 2.
```
In addition, increased our minimum coverage number.
=> display CI failure based on coverage

pyproject.toml
Update Wagtail to 6.3. Reviewed 6.3 LTS [Release Notes](https://docs.wagtail.org/en/stable/releases/6.3.html)
=> Update Wagtail to LTS 6.3

hawc/apps/assessment/templates/assessment/assessment_detail.html
Fixed bug where publish items is hidden from project managers if data extraction and study evaluation modules are disabled; we want to show that in any case.
This is on the assessment actions menu for a project manager `/assessment/:id/`
=> show publish items regardless of which modules are enabled

hawc/apps/animal/exports.py, pyproject.toml
We recently switched from groupby to pivot to improve performance of data frame exports (#1099), but pivots can fail if there are duplicated data in the pivot table.  This PR drops duplicates prior to creating the pivot, in the event that there are duplicates.
This was identified in a rare case, where it appears a user entered multiple dosing regime dose groups that all have the same dose units. A subsequent PR will prevent data entry to prevent these issues.
Bonus - upgrade [django](https://www.djangoproject.com/weblog/2024/dec/04/security-releases/)
=> drop duplicates for pandas pivots

hawc/apps/common/renderers.py
Fix bug related to casting an nullable int64 field into a "-" string. Now, null values in a pandas data frame will be shown using the native null string format for column data type. For Int64 values, this will be <NA>, and None for string values
=> fix html export bug

hawc/apps/assessment/templates/assessment/assessment_detail.html
Reorder the team-member information to show public, listed, locked information first. This is generally the information that's most important when reviewing assessments
=> assessment detail page restructuring

hawc/apps/assessment/managers.py, hawc/apps/common/serializers.py, hawc/apps/lit/managers.py, tests/data/fixtures/db.yaml, tests/hawc/apps/common/test_serializer.py, tests/hawc/apps/lit/test_filterset.py, tests/hawc/apps/lit/test_serializers.py, tests/hawc/apps/test_utils.py, tests/integration/test_lit.py
- Increase test coverage for the lit module:
- Test reference filterset 
- Test Workflows
- Fix labeled items search bug
- Fix invalid literature workflow in the fixture
- Add test for serializer FilterReferences
=> Increase lit test coverage

client/hawc_client/animal.py, docs/docs/client.md
Update client so you can request unpublished BMD modeling for an assessment.
=> add unpublished argument to bmd endpoints client

hawc/apps/myuser/management/commands/scrub_db.py, hawc/apps/myuser/synthetic.py, pyproject.toml, tests/hawc/apps/myuser/test_synthetic.py
The [Faker](https://pypi.org/project/Faker/) package is only used to generate synthetic user data and we're not really taking advantage of the complexities of the package. 
Rewrite, removing the package, using just the standard library.
=> generate fake user data; remove faker dependency

hawc/apps/lit/exports.py, tests/hawc/apps/lit/test_exports.py
If a reference export is requested and an assessment has no references, or no references with tags, it returns an export that indicates that No Data are available. Previously, an error would occur.
=> empty long reference export check

hawc/apps/common/middleware.py, hawc/main/settings/base.py, hawc/templates/base.html, tests/hawc/apps/common/test_middleware.py
Make all timezones aware. Adapted (adding tests) from https://www.loopwerk.io/articles/2025/django-local-times/
=> Show correct datetime timezone for users
