shapiromatron/hawc

project/animal/models.py
project/invitro/exports.py
project/invitro/models.py
project/invitro/serializers.py
project/invitro/views.py
project/summary/forms.py
project/summary/migrations/0004_datapivotquery_export_format.py
project/summary/models.py
project/templates/summary/datapivot_form.html

Design two different format-styles for in-vitro data-pivots- one where data are aggregated by Endpoint, and one where data are aggregated by Endpoint-group.

Add multiple formats to in-vitro data pivots

---

project/animal/exports.py
project/static/summary/js/data_pivot.js

1. Add new field for conditional formatting - true/false pairwise significant
2. re-order when style overrides are applied - first conditional, then any row-level overrides
3. add null-case for conditional formatting so that if no style is applied, there's no change.

Data pivot conditional point formatting

---

project/study/templatetags/get_at_index.py
project/study/views.py
project/templates/study/sq_edit.html

Add study quality metric descriptions to risk of bias edit page.

Add metric description

---

project/animal/forms.py
project/animal/lookups.py
project/animal/views.py
project/static/animal/js/endpoint.js

Request to filter by by endpoint name, and order results by endpoint name.

on endpoint-filter list, filter by endpoint name

---

project/assessment/views.py
project/invitro/api.py
project/invitro/models.py
project/invitro/serializers.py
project/invitro/urls.py
project/templates/assessment/clean_extracted_data.html

Added ability to clean IV chemical fields in text-cleanup

More cleanup options

---

project/static/css/hawc.css
project/templates/hawc/table_inline_formset.html
project/templates/riskofbias/reviewers_form.html

Adds a button to the Risk of Bias Reviewer Form template for copying a reviewer to every study in the assessment.

RoB reviewers can be copied to every study on reviewer form

---

project/assets/robTable/components/CrossStudyDisplay/index.js
project/assets/robTable/components/DomainDisplay/index.js
project/assets/robTable/components/MetricForm/MetricForm.css
project/assets/robTable/components/MetricForm/index.js
project/assets/robTable/components/ScoreDisplay/ScoreDisplay.css
project/assets/robTable/components/ScoreDisplay/index.js
project/assets/robTable/components/ScoreForm/index.js
project/assets/robTable/containers/RiskOfBiasForm/index.js

Adds a 'Copy Notes' button to each displayed review on the RoB Final Review edit page, which copes the text of the selected review into the review editor.
Splits MetricDisplay component into MetricDisplay and MetricForm.

Copy review notes

---

project/animal/models.py
project/riskofbias/models.py
project/study/models.py
project/summary/models.py
project/templates/animal/animalgroup_confirm_delete.html
project/templates/animal/animalgroup_detail.html
project/templates/animal/animalgroup_form.html
project/templates/animal/dosingregime_form.html
project/templates/animal/endpoint_confirm_delete.html
project/templates/animal/endpoint_copy_selector.html
project/templates/animal/endpoint_detail.html
project/templates/animal/endpoint_form.html
project/templates/animal/experiment_confirm_delete.html
project/templates/animal/experiment_detail.html
project/templates/animal/experiment_form.html
project/templates/lit/reference_detail.html
project/templates/riskofbias/rob_detail.html
project/templates/riskofbias/rob_edit.html
project/templates/study/attachment_confirm_delete.html
project/templates/study/attachment_form.html
project/templates/study/study_confirm_delete.html
project/templates/study/study_detail.html
project/templates/study/study_form.html
project/templates/summary/datapivot_detail.html
project/templates/summary/summarytext_form.html
project/templates/summary/summarytext_list.html

https://trello.com/c/DSCzZg9Y/319-use-get-crumbs-everywhere-8-8
Replace template title and breadcrumbs with model.get_crumbs() and title/breadcrumb templates.

use basic get_crumbs where able to

---

.gitignore
project/devServer.js
project/package.json
project/webpack.config.dev.js

Adds Webpack Dashboard, which provides a much nicer UX to Webpack, and Happypack, which decreases webpack compile times

Webpack dashboard

---

project/assets/epi/Outcome.js
project/assets/epi/OutcomeListTable.js
project/epi/forms.py
project/epi/lookups.py
project/invitro/forms.py
project/invitro/lookups.py
project/templates/epi/outcome_list.html
project/templates/epimeta/metaresult_list.html

Per emails in response to epi and invitro endpoint filtering forms, revisions to the forms are necessary. 
https://trello.com/c/QWE2w352/508-endpoint-filtering-form-revisions
**Remove**
Chemical Source
Chemical Purity
**Add**
Cell Type - Cell Type
Cell Type - Tissue
**Remove**
Age of Measurement
**Add**
Study population - (study design, age profile, source, country)
Study population -> Exposure - metric

Endpoint filter revisions

---

project/invitro/forms.py
project/invitro/lookups.py
project/templates/invitro/ivexperiment_form.html

Finishes up Trello card [In vitro - add CRUD forms](https://trello.com/c/9UqVxsSF/378-in-vitro-add-crud-forms-40-18)

add AutoCompleteWidget to invitro fields that would benefit

---

project/assets/mgmt/TaskAssignments/components/Assignments/index.js
project/assets/mgmt/TaskAssignments/components/Task/index.js
project/assets/mgmt/TaskAssignments/components/TaskLabel/index.js
project/assets/mgmt/TaskTable/actions.js
project/assets/mgmt/TaskTable/components/StatusLabel/index.js
project/assets/mgmt/TaskTable/components/TaskForm/index.js
project/assets/mgmt/TaskTable/components/TaskLabel/index.js
project/assets/mgmt/TaskTable/components/TaskStudy/index.js
project/assets/mgmt/TaskTable/components/UserAutocomplete/index.js
project/assets/mgmt/TaskTable/containers/TaskToggle/TaskToggle.css
project/assets/mgmt/TaskTable/containers/TaskToggle/index.js
project/mgmt/serializers.py
project/templates/mgmt/assessment_details.html
project/templates/mgmt/user_assessment_assignments.html
project/templates/mgmt/user_assignments.html

Closes https://trello.com/c/bokvqdX3/543-8-allow-pm-tasks-to-be-edited-individually

Task edits

---

.gitignore
Makefile
bin/dev.sh
docs/source/dev_setup.rst
docs/source/reference.rst
project/assets/epi/ResultGroupTable.js
project/assets/shared/utils.js
project/epi/models.py

See footnote b in this example: 
Footnote is only added when a CI is calculated, not manually entered.

Add  footnote to indicate when epi CI are calculated in HAWC

---

project/assets/lit/TagTreeViz.js

Fixes https://trello.com/c/65Earp8l/567-display-issue-benzene

adjust TagTreeViz svg.viewBox if graph gets too long.

---

project/assets/robTable/components/Completeness/index.js
project/assets/robTable/components/DomainDisplay/index.js
project/assets/robTable/components/MetricForm/index.js
project/assets/robTable/components/ScoreForm/index.js
project/assets/robTable/containers/RiskOfBiasForm/index.js
project/assets/shared/components/ScrollToErrorBox/index.js
project/riskofbias/models.py

Rob completeness

---

project/animal/exports.py

Closes https://trello.com/c/vBPo5f3j/605-modify-significance-to-go-up-or-down-based-on-value

animal.EndpointFlatDataPivot: add response direction to significance

---

project/static/css/hawc.css
project/templates/hawc/about.html

Closes https://trello.com/c/DpcA474B/609-add-new-tutorials-page-on-hawc-about-page

add tutorial videos to About page

---

project/templates/hawc/about.html

Closes https://trello.com/c/MhCsVsTG/615-add-more-training-videos
5a, 5b, 5c
6c, 6c1, 6d
7c
8b, 8e
11c1, 11c2, 11c3
12a, 12b

add additional training videos

---

project/templates/hawc/about.html

Closes https://trello.com/c/SH6VCYpz/622-add-more-hawc-training-videos

add latest training videos

---

project/study/forms.py

Closes https://trello.com/c/lCMqJNw0/625-copy-studies-across-assessments-page-change

remove 'epi only' text from study copy form

---

project/templates/assessment/sidebar.html

Closes https://trello.com/c/BHWYoikp/624-modify-rob-sidebar-link-display

always show RoB link in sidebar

---

project/assessment/templates/assessment/assessment_detail.html

Closes https://trello.com/c/MVXMP86Q/635-remove-private-views-from-public-assessment-detail-page

remove private views from public assessment-details page

---

project/animal/assets/animal/BMDResult.js
project/animal/assets/animal/Endpoint.js
project/animal/assets/animal/EndpointCriticalDose.js
project/animal/exports.py
project/animal/models.py
project/animal/serializers.py
project/bmd/assets/bmd/components/BMROptionModal.js
project/bmd/assets/bmd/components/BaseModal.js
project/bmd/assets/bmd/components/ModelOptionModal.js
project/bmd/assets/bmd/components/OutputModal.js
project/bmd/assets/bmd/components/Recommendation.js
project/bmd/assets/bmd/components/RecommendationNotes.js
project/bmd/assets/bmd/containers/Tabs.js
project/bmd/assets/bmd/models/model.js
project/bmd/models.py
requirements/base.txt

Implements changes for #123; some were tabled to do later as they require a major refactoring.

bmds execution bugfixes

---

project/animal/forms.py
project/animal/lookups.py

Allows filtering the endpoint list by effect subtype.
resolves #100

Added animal bioassay filter by effect subtype

---

project/animal/serializers.py
project/epi/serializers.py
project/invitro/serializers.py

Adding study short citation to individual cleanup fields

---

project/summary/assets/summary/CrossviewPlot.js

Add points dose-response points on crossview when hovering to display mean response values for each dose group. This was requested to better understand the spline curve-fit. The card did not specify to only show points on hover, but after attempting to display all points at all times, it felt too overwhelming and therefore was modified for the hover-only case.
Not extensively tested on IE11 or the svg/png rendering upon download; I don't anticipate issues, but it will be good to check after merging and issue hotfix if required (difficult to test locally).

when hovering, add points on crossview

---

project/summary/assets/summary/RoBHeatmapPlot.js
project/summary/assets/summaryForms/RoBHeatmapForm.js

Add news option; if no value is present defaults to short-citation
.

ROB heatmap - add new option to show which label to display

---

.gitignore
project/assessment/forms.py
project/assessment/views.py

Implements #144; added a little more magic to the email so that it reports the prior page the client was currently visiting.

make login required to contact; capture prior page

---

hawc/apps/animal/admin.py
hawc/apps/assessment/admin.py
hawc/apps/bmd/admin.py
hawc/apps/epi/admin.py
hawc/apps/lit/admin.py
hawc/apps/mgmt/admin.py
hawc/apps/myuser/admin.py
hawc/apps/myuser/tasks.py
hawc/apps/riskofbias/admin.py
hawc/apps/study/admin.py
hawc/apps/summary/admin.py

- Create celery admin task to test success of celery execution
- Update admin views for more default model views

Admin updates

---

.github/workflows/main.yml
Makefile
docs/source/server_setup.rst
frontend/epi/split.js
hawc/apps/lit/apps.py
hawc/main/settings/base.py
requirements/base.txt
tests/apps/lit/test_lit_imports.py

- hotfix - repair export of epi.js code for template use
- update `litter_getter==0.2.6`
- Use new `PUBMED_API_KEY` where needed
- Use new HERO API

Hero search

---

requirements/base.txt

update django version

---

Makefile
docs/source/dev_setup.rst
hawc/apps/lit/models.py
hawc/main/settings/unittest.py
pytest.ini
requirements/base.txt

- fix test settings to work locally
- update django-taggit library

Django taggit

---

frontend/lit/EditReferenceContainer.js
frontend/lit/NestedTag.js
frontend/lit/Reference.js
frontend/lit/ReferencesViewer.js
hawc/apps/lit/forms.py
hawc/apps/lit/models.py
hawc/apps/lit/templates/lit/reference_detail.html
hawc/apps/lit/templates/lit/search_tags_edit.html
hawc/apps/lit/views.py
hawc/main/settings/base.py
hawc/static/css/hawc.css

- new feature; save literature tag (expanded/collapsed) settings for a user
- increased maximum Pubmed query size to 10,000
- improve detail reference view layout
- improve layout for literature tagging view
- add search list to all literature tag views
- add HAWC id to reference identifiers

lit improvements

---

frontend/summary/dataPivot/DataPivot.js
hawc/apps/animal/exports.py

- fixed error where 500 thrown if data  was not reported for an endpoint

fix data pivot error

---

docs/source/api.rst
hawc/apps/animal/api.py
hawc/apps/animal/urls.py
hawc/apps/animal/views.py
hawc/apps/assessment/templates/assessment/assessment_downloads.html
hawc/apps/common/api.py
hawc/apps/common/helper.py
hawc/apps/epi/api.py
hawc/apps/epi/urls.py
hawc/apps/epi/views.py
hawc/apps/epimeta/api.py
hawc/apps/epimeta/urls.py
hawc/apps/epimeta/views.py
hawc/apps/invitro/api.py
hawc/apps/invitro/urls.py
hawc/apps/invitro/views.py
hawc/apps/lit/api.py
hawc/apps/lit/templates/lit/overview.html
hawc/apps/lit/templates/lit/reference_list.html
hawc/apps/lit/templates/lit/reference_visual.html
hawc/apps/lit/urls.py
hawc/apps/lit/views.py
hawc/apps/riskofbias/api.py
hawc/apps/riskofbias/urls.py
hawc/apps/riskofbias/views.py
hawc/client/__init__.py

Create a REST client in Python.

Python client

---

frontend/lit/TagTreeViz.js

- wrap text in literature tree nodes in case it grows too long

wrap text in literature tree nodes in case it grows too long

---

hawc/__init__.py
hawc/apps/animal/api.py
hawc/apps/assessment/serializers.py
hawc/apps/common/serializers.py
hawc/apps/epi/api.py
hawc/apps/epimeta/api.py
hawc/apps/invitro/api.py
hawc/apps/lit/api.py
hawc/apps/lit/serializers.py
hawc/apps/riskofbias/api.py
hawc/main/urls.py
requirements/base.txt
tests/main/test_openapi.py

Added endpoint "/openapi" that generates an OpenAPI spec of HAWC's API endpoints.

OpenAPI (Swagger API) integration

---

frontend/lit/ReferencesViewer.js
hawc/apps/lit/api.py
hawc/apps/lit/urls.py
tests/apps/lit/test_lit_api.py

These were accidentally removed in an regression; now we have a test to ensure they'll stick around...

Add back references by tag exports

---

frontend/summary/summary/ExploreHeatmapPlot.js

Blacklist now shows up as checkboxes, detail table is updated dynamically.

Update heatmap blacklist / detail table

---

frontend/summary/summary/ExploreHeatmap.js
frontend/summary/summary/ExploreHeatmapPlot.js
frontend/summary/summary/heatmap/FilterWidgetContainer.js
frontend/summary/summaryForms/heatmap/VisualCustomizationPanel.js
frontend/summary/summaryForms/stores/ExploratoryHeatmapStore.js

- Added autosize option for heatmap, takes up container width and keeps screen aspect ratio.
- Added <Empty> row to filter widget when data is empty string.
- Also fixes a bug where integer data would not display in widget

Heatmap autosize

---

frontend/assets/shared/components/VisualToolbar/index.js
frontend/summary/summary/ExploreHeatmap.js
frontend/summary/summary/ExploreHeatmapPlot.js
frontend/summary/summary/heatmap/DatasetTable.js
frontend/summary/summary/heatmap/FilterWidgetContainer.js
hawc/static/css/d3.css

Changed heatmap layout to use flexbox.
- Data table grows as filters grow

Heatmap layout

---

hawc/apps/assessment/models.py
hawc/apps/assessment/templates/assessment/assessment_detail.html
hawc/apps/assessment/urls.py
hawc/apps/assessment/views.py
tests/apps/assessment/test_assessment_views.py

Add new django view which allows a team-member to flush an assessment cache.

Clear assessment cache view

---

frontend/summary/dataPivot/DataPivotVisualization.js
hawc/apps/summary/forms.py
hawc/apps/summary/templates/summary/datapivot_copy_selector.html
hawc/apps/summary/views.py
requirements/base.txt

- fix data pivot text-alignment bug
- use standard crispy forms for data pivot selector instead of custom
- update django to newest release

Data pivot style alignment

---

frontend/lit/EditReferenceContainer.js
frontend/lit/Reference.js
hawc/apps/lit/templates/lit/reference_detail.html

Update reference list-layout view to show all tags which have been applied to a reference

show all tags in standard reference detail views

---

hawc/apps/assessment/admin.py
hawc/apps/assessment/models.py
hawc/templates/admin/assessment/blog/change_form.html

Screenshot of blog preview in admin (fyi @rabstejnek):

added admin blog preview and raw html text

---

frontend/study/Study.js
frontend/utils/DescriptiveTable.js
hawc/apps/study/templates/study/study_detail.html

Hotfix: preformatted strings on study table

---

hawc/apps/assessment/admin.py
hawc/apps/lit/managers.py

Added an assessment admin action to delete orphaned reference tags.

Delete orphaned tags

---

hawc/apps/assessment/views.py
tests/hawc/apps/assessment/test_assessment_views.py

- fix error on `/about/` 
- add test to check for error case

fix error on /about/ and add test to check for error case

---

compose/django/Dockerfile
requirements/base.txt

Add netcat since it's required for `wait-for.sh`; update a few dependencies to fix pip warnings

deployment updates

---

hawc/apps/epi/models.py

/epi/api/assessment/100500071/study-heatmap/?unpublished=True

Hotfix: study heatmap API

---

hawc/apps/animal/lookups.py

Fixes `/selectable/animal-endpointbyassessmenttextlookup/`
SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT COUNT(*) FROM (SELECT DISTINCT ON ("assessment_baseen...

apply same order as distinct clause

---

hawc/apps/assessment/views.py
hawc/apps/common/context_processors.py
hawc/apps/common/management/commands/set_git_commit.py
hawc/main/settings/base.py
hawc/services/utils/git.py
hawc/static/css/epa.css
hawc/static/css/hawc.css
hawc/templates/base.html
hawc/templates/hawc/about.html
hawc/templates/includes/css.html
hawc/templates/includes/epa/footer.html
hawc/templates/includes/epa/header.html
hawc/templates/includes/footer.html
tests/hawc/services/utils/test_git.py

- add prime footer and cache
- add epa header/footer and cache

Header footer

---

frontend/animal/EndpointListApp/Widgets.js
frontend/assets/shared/components/Autocomplete/index.js
frontend/assets/shared/components/CheckboxInput.js
frontend/assets/shared/components/FloatInput.js
frontend/assets/shared/components/HelpText.js
frontend/assets/shared/components/IntegerInput.js
frontend/assets/shared/components/LabelInput.js
frontend/assets/shared/components/QuillTextInput.js
frontend/assets/shared/components/RadioInput.js
frontend/assets/shared/components/ReactDatePicker.js
frontend/assets/shared/components/SelectInput.js
frontend/assets/shared/components/TextAreaInput.js
frontend/assets/shared/components/TextInput.js
frontend/mgmt/TaskTable/components/StatusSelection.js
frontend/mgmt/TaskTable/components/UserAutocomplete.js
frontend/mgmt/TaskTable/containers/StudyFilter.js
frontend/riskofbias/robScoreCleanup/containers/MetricSelect.js
frontend/riskofbias/robStudyForm/ScoreForm.js
frontend/summary/heatmapTemplate/CustomizeTab.js
frontend/summary/summaryForms/EndpointAggregationFormReact.js
frontend/summary/summaryForms/heatmap/AxisLabelTable.js
frontend/summary/summaryForms/heatmap/DataPanel.js
frontend/summary/summaryForms/heatmap/DetailTable.js
frontend/summary/summaryForms/heatmap/FilterWidgetTable.js
frontend/summary/summaryForms/heatmap/VisualCustomizationPanel.js

Update shared React components used as form inputs

Update bootstrap in React input components

---

hawc/apps/common/management/commands/dump_test_db.py
hawc/apps/common/views.py
tests/data/fixtures/db.yaml
tests/hawc/apps/assessment/test_assessment_views.py
tests/hawc/apps/common/test_common_views.py

referrer sanitize - domain

---

hawc/apps/assessment/api.py
hawc/apps/assessment/urls.py
hawc/apps/assessment/views.py
hawc/apps/vocab/views.py
hawc/main/urls.py
tests/hawc/apps/assessment/test_assessment_api.py

- New location: `/assessment/api/healthcheck/`
- Removed EHV list view login requirement

Move healthcheck URL location

---

hawc/apps/assessment/managers.py
hawc/apps/assessment/models.py
hawc/apps/assessment/views.py
hawc/templates/hawc/about.html
hawc/templates/hawc/home.html
tests/hawc/apps/assessment/test_assessment_models.py

Update content templating logic to take in django template context in the appropriate request framework so that standard context-processors can be used.

update templating logic

---

hawc/apps/assessment/api.py
hawc/apps/assessment/signals.py
hawc/apps/assessment/views.py
hawc/apps/bmd/signals.py
hawc/apps/common/helper.py
hawc/apps/common/models.py
hawc/apps/common/views.py
hawc/apps/epi/signals.py
hawc/apps/lit/forms.py
hawc/apps/lit/managers.py
hawc/apps/lit/models.py
hawc/apps/lit/serializers.py
hawc/apps/mgmt/managers.py
hawc/apps/mgmt/models.py
hawc/apps/riskofbias/models.py
hawc/apps/riskofbias/signals.py
hawc/apps/study/models.py
hawc/main/settings/base.py
hawc/main/settings/dev.py
hawc/main/settings/local.example.py
hawc/services/epa/hero.py
hawc/services/nih/pubmed.py
hawc/services/utils/ris.py

Use best-practices in in logging instead of using the root logger.
- Use `logging.getLogger(__name__)` instead of the root logger
- Update base and dev settings to better screen data

update logging configuration

---

hawc/apps/assessment/templates/assessment/assessment_list.html
hawc/apps/myuser/views.py
hawc/templates/assessment-rooted.html

Minor layout changes and renaming from content review

layout revisions from review

---

hawc/apps/assessment/forms.py
hawc/apps/assessment/templates/assessment/assessment_list.html
hawc/apps/assessment/views.py

Add pagination to the public assessment list and the user's assessment list. Each page displays 50 assessments.

Paginate assessment lists

---

client/hawc_client/__init__.py
client/hawc_client/session.py
hawc/apps/myuser/api.py
hawc/apps/myuser/urls.py
tests/client/test_client.py
tests/hawc/apps/myuser/test_api.py

Adds a check in the `client.set_authentication_token` function which raises an exception if the auth token is invalid.

Client checks if auth tokens are valid

---

hawc/apps/myuser/management/commands/scrub_db.py

in scrub db command, set Site to localhost to prevent admin urls going to production site

set base site to localhost when scrubbing db

---

frontend/shared/components/VisualToolbar.js

Standardizes PNG download button text to make using playwright locator simpler.

Standardize download button text for Assessment Visuals download script

---

client/Makefile
client/hawc_client/__init__.py
client/setup.cfg
docs/docs/client.md

Supporting code for latest release: https://pypi.org/project/hawc-client/

release hawc_client 2023.1

---

docs/docs/development.md

Updated development documentation.
- kept python version 3.9
- yarn version --> 1
- postgresql >=12
- tested with python 3.9, latest version of postgresql (v15.2), and yarn v1.22.19

updated python, yarn and postgresql versions in docs

---

hawc/apps/assessment/forms.py
hawc/apps/assessment/templates/assessment/assessmentvalue_form.html
tests/hawc/apps/assessment/test_forms.py

added header to Update Assessment Value page

---

hawc/apps/assessment/migrations/0036_assessment_enable_downloads_and_more.py
hawc/apps/summary/migrations/0008_auto_20160608_1109.py

make sync-dev failed on manage migrate due to some migrations being out of order. Danny R helped fix the dependencies

added dependencies to fix failed migrations

---

hawc/apps/riskofbias/templates/riskofbias/rob_edit.html

- added help text to rob study eval update page

added rob help text to page

---

hawc/apps/animal/constants.py
hawc/apps/animal/migrations/0023_update_help_text.py
hawc/apps/animal/models.py
tests/data/api/api-animal-metadata.json

- added pubertal field to ExerimentType
- added Juvenile field to Lifestage exposed/assessed
- updated migration

added pubertal fields to ani constants

---

Makefile
docs/docs/deployment.md
hawc/__init__.py
hawc/apps/assessment/actions/audit.py
hawc/apps/assessment/api/viewsets.py
hawc/apps/assessment/templates/assessment/assessment_detail.html
hawc/apps/assessment/templates/assessment/assessment_downloads.html
hawc/apps/assessment/views.py
hawc/apps/lit/forms.py
hawc/apps/mgmt/filterset.py
hawc/apps/study/constants.py
hawc/apps/study/filterset.py
hawc/apps/study/forms.py
hawc/apps/study/models.py
hawc/apps/study/templates/study/study_list.html
hawc/constants.py
hawc/main/settings/unittest.py
make.bat
requirements/production.txt
tests/data/fixtures/db.yaml

1. Update and standardize development Makefile commands
2. Update hawc version to 2023.2
3. Fix API 500 error on audit views
4. Fix db fixture for assessment values
5. remove Assessment Values feature flags (release)
6. remove Eco feature flags (release)

release eco + values

---

hawc/apps/assessment/filterset.py
hawc/apps/assessment/forms.py
hawc/apps/assessment/templates/assessment/assessment_log_list.html
hawc/apps/assessment/views.py
hawc/apps/common/filterset.py
tests/hawc/apps/assessment/test_forms.py

Swap log filter form to a filterset, with expandable inline UI
before:
after:

swap log form to inline

---

hawc/apps/common/autocomplete/registry.py
hawc/apps/study/forms.py
hawc/apps/summary/forms.py

* Use soft .get for accessing cleaned_data
* Use TypedChoiceField instead of IntegerField with a select widget
* Wrap autocomplete in a try/except for value error

fixes from security scan

---

hawc/apps/common/templates/common/crispy_layout_filter_field.html
hawc/apps/lit/filterset.py
hawc/apps/lit/views.py
hawc/apps/study/filterset.py
hawc/apps/study/views.py

- Add authors and year to reference filterset.
- Add pagination filter to study filterset
- Add border to inline 'X' button so it doesn't blend in with checkbox appended fields

update ref filterset

---

hawc/apps/common/dynamic_forms/__init__.py
hawc/apps/common/dynamic_forms/constants.py
hawc/apps/common/dynamic_forms/fields.py
hawc/apps/common/dynamic_forms/forms.py
hawc/apps/common/dynamic_forms/schemas.py
hawc/apps/common/filterset.py
hawc/apps/common/forms.py
hawc/apps/common/templates/common/dynamic_form.html
hawc/apps/common/widgets.py
tests/hawc/apps/common/dynamic_forms/conftest.py
tests/hawc/apps/common/dynamic_forms/test_fields.py
tests/hawc/apps/common/dynamic_forms/test_forms.py
tests/hawc/apps/common/dynamic_forms/test_schemas.py

Vendor dynamic forms from prior work. Since this is needed by both #876 and #882, so we merge this in first.

vendor dynamic forms

---

compose/app/Dockerfile
compose/nginx/Dockerfile
requirements/base.txt

1. Remove git from djagno applications
2. Update django 
3. Update nginx base image

version updates

---

hawc/apps/animal/models.py
tests/hawc/apps/animal/test_models.py

Write a suite of tests to ensure that we're not dividing by zero in some calculation (observed with some strangely entered data extractions).

dichotomous percent control - check for division by zero

---

.github/workflows/main.yml
.readthedocs.yml
client/pyproject.toml
compose/app/Dockerfile
docs/docs/development.md
pyproject.toml

Upgrade from python 3.11 to [python 3.12](https://docs.python.org/3/whatsnew/3.12.html).

python 3.12

---

hawc/__init__.py
hawc/main/settings/staging.py
hawc/main/urls.py
requirements/base.txt
requirements/production.txt

Release 2024.Q1
- Add the release version to sentry if available.
- Add mgmt API endpoints to open api specification

2024.Q1 release

---

hawc/apps/myuser/views.py

Add get_success_url so that updating a user profile properly redirects.

fix profile update redirect

---

frontend/lit/components/Reference.js
hawc/apps/udf/templates/udf/fragments/binding_edit_row.html
hawc/apps/udf/templates/udf/udfbinding_list.html

Fixes overflow literature reference IDs and UDF HTMX conditionals

Fix bugs from lit demo

---

pyproject.toml

https://www.djangoproject.com/weblog/2024/jul/09/security-releases/

update django from 5.0.6 to 5.0.7

---

pyproject.toml

Upgrade django to 5.1

---

hawc/apps/myuser/managers.py
tests/hawc/apps/myuser/test_managers.py

Fix the manage.py createsuperuser command!

fix create_superuser command

---

hawc/apps/assessment/forms.py
hawc/apps/assessment/management/commands/chemicals.py
hawc/apps/common/management/commands/load_test_db.py
hawc/apps/common/management/commands/set_git_commit.py
hawc/apps/common/urls.py
hawc/apps/eco/admin.py
hawc/apps/eco/exports.py
hawc/apps/epiv2/exports.py
hawc/apps/hawc_admin/methods/growth.py
hawc/apps/lit/management/commands/doi.py
hawc/apps/lit/managers.py
hawc/apps/lit/models.py
hawc/apps/riskofbias/actions/rob_clone.py
hawc/apps/summary/models.py
hawc/apps/summary/table_serializers.py
hawc/main/settings/base.py
hawc/main/settings/unittest.py
hawc/main/urls.py
hawc/services/epa/hero.py
hawc/services/utils/doi.py
hawc/tools/tables/set/table.py

Within the hawc package, make all imports relative instead of absolute

make all hawc imports relative instead of absolute

---

frontend/package.json
frontend/yarn.lock

Update to the latest version of express. This is just used for our developer environment.

update npm express

---

.github/workflows/main.yml

Add a new coverage artifact to our workflow. Rename some of our existing artifacts.

Add coverage artifact

---

client/hawc_client/__init__.py
docs/docs/client.md
hawc/__init__.py

* Update release version to 2024.Q3

release 2024.Q3

---

.github/workflows/main.yml

Use [uv](https://docs.astral.sh/uv/). in github actions instead of pip to speed up installs. This speeds up installs by around a minute (30s for the backend job, and 30s for integration).
Also removed the wheel building and artifacts, since that is handled by the github action.

github action - switch to uv

---

Makefile
client/hawc_client/__init__.py
client/pyproject.toml
docs/docs/client.md
hawc/__init__.py
hawc/apps/assessment/managers.py

Prepare for next quarterly release

release 2024.Q4

---

frontend/shared/utils/HAWCUtils.js
hawc/apps/animal/templates/animal/animalgroup_form.html
hawc/apps/epi/templates/epi/result_form.html

No longer needed; https://caniuse.com/template-literals

remove HAWCUtils.printf

---

frontend/shared/components/ConfirmDeleteButton.js
frontend/shared/nestedTagEditor/components/EditNode.js
frontend/shared/nestedTagEditor/components/Node.js
frontend/shared/nestedTagEditor/store.js
hawc/apps/lit/views.py

Show tag counts on update tag page, and update the Delete button text depending on tag count + tag children

Update tag show counts

---

hawc/apps/common/exceptions.py
hawc/main/settings/base.py

Remove settings noise from reports.

Remove settings from exception report

---

client/hawc_client/__init__.py
compose/app/Dockerfile
compose/nginx/Dockerfile
compose/redis/Dockerfile
docs/docs/client.md
frontend/summary/dataPivot/DataPivotUtilities.js
hawc/__init__.py
hawc/apps/assessment/views.py
hawc/apps/summary/admin.py

Prepare release candidate with a number of minor changes based on staging deployments.

prepare 2025.1rc1
